name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Display tag name
        run: echo "Tag name is ${{ github.event.release.name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve wheel artifacts for release
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ github.event.release.name }}-wheels-.*
          name_is_regexp: true
          repo: ${{ github.repository }}
          workflow: build.yml
          path: ./dist-raw
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve SDIST artifacts for release
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ github.event.release.name }}-sdist
          repo: ${{ github.repository }}
          workflow: build.yml
          path: ./dist-raw
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Flatten artifacts into dist
        run: |
          mkdir -p ./dist
          find ./dist-raw -name '*.whl' -exec mv {} ./dist/ \;
          find ./dist-raw -name '*.tar.gz' -exec mv {} ./dist/ \;

      - name: Display structure of downloaded files
        run: ls -laR
        working-directory: ./dist

      - name: Publish to PyPI
        if: ${{ startsWith(github.event.release.name, 'v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: ./dist

      - name: Publish to Test PyPI
        if: ${{ startsWith(github.event.release.name, 'test-') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          packages-dir: ./dist
