name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  # Current issues:
  # - The release name recovered seems to be wrong sometimes
  # - The structure of a release is wrong to automate releasing - consider Twine instead
  
  retrieve_artifacts:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve wheel artifacts for release
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ github.event.release.name }}-wheels
          repo: ${{ github.repository }}
          workflow: build.yml
          path: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve SDIST artifacts for release
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ github.event.release.name }}-sdist
          repo: ${{ github.repository }}
          workflow: build.yml
          path: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Test step for debugging
      - name: Display structure of downloaded files
        run: ls -laR
        working-directory: ./dist

      - name: Release code as new release on Pypi
        if: ${{ startsWith('v', github.event.release.name) }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: https://PREVENTFORTESTING.upload.pypi.org/legacy/
          verbose: true
      
      - name: "TEST: Release code as new release on Test Pypi"
        if: ${{ startsWith('test-',github.event.release.name) }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
