name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  check_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure wheels exist for this release name
        id: wheels_exist
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: ${{ github.event.release.name }}-wheels
      - name: Ensure SDIST exists for this release name
        id: sdist_exists
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: ${{ github.event.release.name }}-sdist
      - name: Fail if no wheels or SDIST exists
        run: |
          if [ -z "${{ steps.wheels_exist.outputs.exists }}" ]; then
            echo "No wheels found for release ${{ github.event.release.name }}";
            exit 1;
          fi

          if [ -z "${{ steps.sdist_exists.outputs.exists }}" ]; then
            echo "No wheels found for release ${{ github.event.release.name }}";
            exit 1;
          fi
  
  retrieve_artifacts:
    runs-on: ubuntu-latest
    needs: check_artifacts
    steps:
      - name: Retrieve wheel artifacts for release
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.release.name }}-wheels
          path: dist/*.whl
      - name: Retrieve SDIST artifacts for release
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.release.name }}-sdist
          path: dist/*.tar.gz

  deploy:
    needs: [check_artifacts, retrieve_artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Release code as new release on Pypi
        if: ${{ startsWith(github.event.release.name,'v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: https://PREVENTFORTESTING.upload.pypi.org/legacy/
          verbose: true
      
      - name: "TEST: Release code as new release on Test Pypi"
        if: ${{ startsWith(github.event.release.name,'test-') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
