name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  
  retrieve_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve wheel artifacts for release
        uses: dawidd6/action-download-artifact@v2
        with:
          # name: ${{ github.event.release.name }}-wheels
          repo: ${{ github.repository }}
          workflow: build.yml
          path: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Retrieve SDIST artifacts for release
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     name: ${{ github.event.release.name }}-sdist
      #     repo: ${{ github.repository }}
      #     workflow: build.yml
      #     path: ./dist
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dist

  deploy:
    needs: retrieve_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Release code as new release on Pypi
        if: ${{ startsWith(github.event.release.name,'v') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: https://PREVENTFORTESTING.upload.pypi.org/legacy/
          verbose: true
      
      - name: "TEST: Release code as new release on Test Pypi"
        if: ${{ startsWith(github.event.release.name,'test-') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
